- hemlock/TEAM
by the way, thanks for setting this up!
> create team "hemlock"

- ryangjchandler/README.md
- ryangjchandler/TEAM
> chore: add ryangjchandler team

- PastaXp/TEAM
> Add PastaXp team

- c_chads/README.md
- c_chads/TEAM
> we cool skeleton people (please add our team)

- largebitmap/README.md
- largebitmap/TEAM
> 💪 large 🧠 bitmap 🤳 (@jordanlewis @justinj)

- ඞ/README.md
- ඞ/TEAM
I am only the messenger, conforming to @RDambrosio016 's disturbingly amogus wishes...
Looking forward to the jam! Let's get started!
> Add team impostors - team impostors is sus ඞ

- dank/README.md
- dank/TEAM
> Add team dank

- Bee/README.md
- Bee/TEAM
> Add Bee Team

- lue/README.md
- lue/TEAM
> add team lue

- LexicalCrimes/README.md
- LexicalCrimes/TEAM
A bit late!
**Team Members:**
---
@mufeedvh
@Asjidkalam
> Add team LexicalCrimes

- samtara/README.md
- samtara/TEAM
> Add Team Samtara

- MarkSideways/README.md
- MarkSideways/TEAM
A solo team consisting of @blakeohare
> Add directory for MarkSideways

- confined/README.md
- confined/TEAM
> Add confined

- beepbeepbeep/README.md
- beepbeepbeep/TEAM
> add beepbeepbeep

- DRUN/README.md
- DRUN/TEAM
Hi!
Decided to join the langjam ;) Probably language will stay more in draft than concrete implementation but it shouldn't hurt to try.
> added DRUN project

- lukehoban/README.md
- lukehoban/TEAM
Work in progress on the Tag language at https://github.com/lukehoban/structtaglang.
> Add lukehoban

- hemlock/TEAM
wasn't able to participate, but thanks for setting it up!
> remove hemlock team

- nsfisis/GRAMMAR
- nsfisis/README.md
- nsfisis/examples/comment.onigiri
- nsfisis/examples/comment2.onigiri
- nsfisis/examples/fizzbuzz.onigiri
- nsfisis/examples/hello_world.onigiri
- nsfisis/onigiri.rb
Thank you for the exciting event!
> [Submit] Team nsfisis: implement a language

- basile-henry/Cargo.toml
- basile-henry/README.md
- basile-henry/comment-errors-test/Cargo.toml
- basile-henry/comment-errors-test/src/main.rs
- basile-henry/comment-errors/Cargo.toml
- basile-henry/comment-errors/src/lib.rs
Thank you for the fun event! :smile:
> [Submit] A proc-macro using first-class comments for error messages

- o/README.md
- o/TEAM
We unfortunately could not do anything useful for this lang jam.
Although, this helped rekindle our passion for making programming
languages for fun (so we've started working on a language outside of
langjam). Thanks jt!
> remove team o

- TeamDailyDose/.gitignore
- TeamDailyDose/BuildTheThing.sh
- TeamDailyDose/CMakeLists.txt
- TeamDailyDose/README.md
- TeamDailyDose/cmake/FetchLagom.cmake
- TeamDailyDose/example.smc
- TeamDailyDose/src/AST.cpp
- TeamDailyDose/src/AST.h
- TeamDailyDose/src/Block.cpp
- TeamDailyDose/src/Block.h
- TeamDailyDose/src/Lexer.cpp
- TeamDailyDose/src/Lexer.h
- TeamDailyDose/src/Parser.cpp
- TeamDailyDose/src/Parser.h
- TeamDailyDose/src/Primitives.cpp
- TeamDailyDose/src/Primitives.h
- TeamDailyDose/src/Scope.cpp
- TeamDailyDose/src/Scope.h
- TeamDailyDose/src/Utils.h
- TeamDailyDose/src/Value.h
- TeamDailyDose/src/main.cpp
Got it done barely in time. 80% of the work was done in the past 6 hours.
> TeamDailyDose: Finish implementing SmallComment! :^)

- ඞ/.gitignore
- ඞ/Cargo.toml
- ඞ/README.md
- ඞ/examples/build_check_comments.sus
- ඞ/examples/build_modify_let.sus
- ඞ/examples/build_parse_string.sus
- ඞ/examples/build_your_own_program.sus
- ඞ/examples/comments.sus
- ඞ/examples/dont_build.sus
- ඞ/examples/just_build.sus
- ඞ/examples/print.sus
- ඞ/src/args.rs
- ඞ/src/ast/mod.rs
- ඞ/src/eval/ast.rs
- ඞ/src/eval/mod.rs
- ඞ/src/eval/value.rs
- ඞ/src/lib.rs
- ඞ/src/main.rs
- ඞ/src/parser/error.rs
- ඞ/src/parser/grammar.rs
- ඞ/src/parser/lexer.rs
- ඞ/src/parser/mod.rs
Just in Time, a (somewhat brittle) meta-programming language where it's not the compiler that shapes how comments influence your program, but _You_!
> ඞ submission

- asrp/README.md
> Small readme update for asrp's submission Stickynotes

- unsound-judgement/Cargo.toml
- unsound-judgement/README.md
- unsound-judgement/TEAM
- unsound-judgement/build.rs
- unsound-judgement/examples/fib.nd
- unsound-judgement/examples/linear_find.nd
- unsound-judgement/ideas/sketch0.txt
- unsound-judgement/rustfmt.toml
- unsound-judgement/src/main.rs
- unsound-judgement/src/parser.rs
- unsound-judgement/src/parser/grammar.lalrpop
- unsound-judgement/src/prelude.nd
- unsound-judgement/src/raw_ast.rs
- unsound-judgement/src/type_check.rs
- unsound-judgement/src/vm.rs
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/.vscode/launch.json
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/.vscodeignore
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/CHANGELOG.md
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/README.md
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/language-configuration.json
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/package.json
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/syntaxes/nanodijkstra.tmLanguage.json
- unsound-judgement/vscode/nanodijkstra-syntax-highlighting/vsc-extension-quickstart.md
Cleanup for #191 
Cleanup:
* landing commits that came in before cut-off
Closes #191
> Cleanup for 191

- DRUN/README.md
- DRUN/deps.edn
- DRUN/src/langjam/core.clj
- DRUN/src/langjam/parser.clj
- DRUN/src/langjam/vm.clj
Cleanup PR for #218 
Cleanup:
* marked as late entry
Closes #218
> Cleanup 218

- unseemly-behavior/README.md
- unseemly-behavior/commentary.unseemly
- unseemly-behavior/fast_fib.commentary
- unseemly-behavior/slow_fib.commentary
Cleanup PR for #220 
Cleanups:
* Lands commits before cut-off
* Fixes conflict
Closes #220
> Cleanup 220

- BenJilks/src/interpreter.c
- BenJilks/src/object.c
- BenJilks/src/object.h
I know this is extremely late, but I noticed my project crashed on a different machine. So here's a quick fix for that.
> BenJilks: Quick fix
